export const GET_CLIENTS = "NEW/GET_CLIENTS";
export const HANDLE_INPUT_UPDATE = "NEW/HANDLE_INPUT_UPDATE";
export const HANDLE_CLIENT_UPDATE = "NEW/HANDLE_CLIENT_UPDATE";
export const RESET_INPUT = "NEW/RESET_INPUT";
